parameters:
    bangpound_guzzle_proxy.routing_loader.class: Bangpound\Bundle\GuzzleProxyBundle\Routing\ProxyLoader

services:
    bangpound_guzzle_proxy.routing_loader:
        class: %bangpound_guzzle_proxy.routing_loader.class%
        arguments: [ %bangpound_guzzle_proxy.endpoints% ]
        tags:
            - { name: routing.loader }
