parameters:
    bangpound_guzzle_proxy.routing_loader.class: Bangpound\Bundle\GuzzleProxyBundle\Routing\ProxyLoader
    bangpound_guzzle_proxy.client.class: GuzzleHttp\Client
    bangpound_guzzle_proxy.listener.guzzle_response.class: Bangpound\Bundle\GuzzleProxyBundle\EventListener\GuzzleResponseListener

services:
    bangpound_guzzle_proxy.routing_loader:
        class: %bangpound_guzzle_proxy.routing_loader.class%
        tags:
            - { name: routing.loader }

    bangpound_guzzle_proxy.listener.guzzle_response:
        class: %bangpound_guzzle_proxy.listener.guzzle_response.class%
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    bangpound_guzzle_proxy.client:
        class: %bangpound_guzzle_proxy.client.class%
        arguments:
            -
                base_url: ~
        abstract: true
